env:
  name: hopper
  id: Hopper-v5
  action_type: continuous
  max_steps: 1000

expert:
  algo: sac
  save_path: models/hopper/expert
  env_seed: 42
  total_timesteps: 1000000

  params:
    policy: MlpPolicy
    learning_rate: 0.001
    buffer_size: 1000000
    learning_starts: 10000
    batch_size: 256
    tau: 0.005
    gamma: 0.99
    train_freq: 1
    gradient_steps: 1
    seed: 42

trajectory_collection:
  output_dir: data/hopper
  random_trajs_seed: 1000000

  train:
    n: 1000
    seed: 100

  valid:
    n: 100
    seed: 2000

  test:
    n: 100
    seed: 30000

policy:
  hidden: 64
  n_hidden_layers: 2
  log_std_min: -5
  log_std_max: 2

reward:
  hidden: 64
  gamma: 0.99

training:
  n_outer_steps: 100
  n_inner_steps: 50000
  n_agent_traj: 100
  lr_outer: 1e-4
  lr_inner: 1e-4
  seed: 42

inner_agent:
  type: sac
  max_grad_norm: 10.0
  use_baseline: false
  normalize_coef: false
  sac:
    lr_q: 1e-3
    buffer_size: 300000
    batch_size: 256
    learning_starts: 500
    tau: 0.005
    alpha: 0.2
    autotune: true
    policy_frequency: 2
    target_network_frequency: 1
    gamma: 0.99

outer_optimizer:
  fisher_reg: 1.0
  max_grad_norm: 1.0
  min_lr: 1e-6
  gamma: 0.99

data:
  expert_train_trajs: data/hopper/expert_train_trajs.pt
  expert_valid_trajs: data/hopper/expert_valid_trajs.pt
  expert_test_trajs:  data/hopper/expert_test_trajs.pt
  random_valid_trajs: data/hopper/random_valid_trajs.pt
  random_test_trajs:  data/hopper/random_test_trajs.pt

checkpoint:
  dir: checkpoints/hopper

logging:
  log_dir: logs
  report_dir: reports
  log_every: 1
