env:
  name: hopper
  id: Hopper-v5
  action_type: continuous
  max_steps: 1000

expert:
  algo: sac
  save_path: models/hopper/expert
  random_seed: 42
  env_seed: 42
  total_timesteps: 1000000

  params:
    policy: MlpPolicy
    learning_rate: 0.001
    buffer_size: 1000000
    learning_starts: 10000
    batch_size: 256
    tau: 0.005
    gamma: 0.99
    train_freq: 1
    gradient_steps: 1
    seed: 42

trajectory_collection:
  output_dir: data/hopper
  random_seed: 42
  env_seed: 42

  train:
    n: 1000

  valid:
    n: 100

  test:
    n: 100

policy:
  hidden: 64
  n_hidden_layers: 2
  log_std_min: -5
  log_std_max: 2

reward:
  hidden: 64
  gamma: 0.99

fisher:
  random_seed: 42
  env_seed: 42
  n_outer_steps: 1000
  n_inner_steps: 100000
  n_agent_traj: 100

  lr_reward: 1e-3
  reg: 1.0
  gamma: 0.99
  max_grad_norm: 1.0

  inner:
    sac_env_seed: 67
    type: sac
    lr_actor: 1e-5
    sac:
      lr_q: 1e-4
      buffer_size: 300000
      batch_size: 256
      learning_starts: 500
      tau: 0.005
      alpha: 0.2
      autotune: true
      policy_frequency: 2
      target_network_frequency: 1
      gamma: 0.99

ttsa:
  random_seed: 42
  env_seed: 42

  n_iterations: 2000
  n_traj_per_step: 20
  metrics_every: 1

  lr_policy: 3e-3
  lr_reward: 3e-4

  gamma: 0.99
  n_cg_steps: 10
  reg: 1e-2

  inner_grad_max_norm: 5.0
  outer_grad_max_norm: 1.0

data:
  expert_train_trajs: data/hopper/expert_train_trajs.pt
  expert_valid_trajs: data/hopper/expert_valid_trajs.pt
  expert_test_trajs:  data/hopper/expert_test_trajs.pt
  random_valid_trajs: data/hopper/random_valid_trajs.pt
  random_test_trajs:  data/hopper/random_test_trajs.pt

checkpoint:
  dir: checkpoints/hopper

logging:
  log_dir: logs
  report_dir: reports
  log_every: 1

evaluation:
  random_seed: 42
  env_seed: 42
  n_agent_traj: 100

  bootstrap:
    enabled: true
    n_samples: 1000
    seed: 42
